### ISSUE TITLE
[BUG] Initial configuration of the windows guest (with KVM) results in a failure boot loop 

### ISSUE THREAD

**Issue by symeonp** [tetrane/reven-community#10]
**Describe the bug**
On the VM setup screen when trying to lighten the OS screen using KVM the VM fails to boot.

**To Reproduce**
This has been tested on Mac OS 11.6 (host) using VMWare Fusion on two OSes both using UEFI:
- Ubuntu 20.04.3 (docker)
- Debian 10 bare metal VM using the installation scripts

**Expected behavior**
Boot the VM and mount the CD

**Screenshots**
[Screenshot](https://pbs.twimg.com/media/FGHqctQXEAkmeEO?format=jpg&name=4096x4096)

**Host Environment**
- REVEN Version 2.10.1.1
- REVEN Edition Free
- REVEN Package Debian/Docker
- Additional information of interest? (e.g. use of Axion AppImage, anything peculiar about your setup)

**Conditions of occurrence**
- Both the VMs were with Intel VT-x/EPT enabled inside the virtual machine

**Logs**
- Can't figure out the logs from the UI

**Additional context**
Let me know how I can check the logs so we can figure out why it's failing. 
Interesting enough, the following screen with the creation of the live snapshot works perfectly
so clearly it's a KVM issue.
Thanks!

**Comment by Quentin01** [comment]
Hi,

It's highly possible the issue lies somewhere near KVM as you said.

The logs you couldn't find are in `TASKS & SESSIONS > Active Sessions > See all > Details` from any page of the Project Manager.

We would also like to have your VMWare fusion version to check online if there is some known issues with nested virtualization using KVM.

It would also help to verify that the nested virtualization is working properly using the distros official QEMU. On either of your REVEN VMs, please run the following commands:
```bash
# Install your OS' QEMU
sudo apt install qemu-kvm qemu-system-x86
# Run the VM manually
qemu-system-x86_64 -enable-kvm -m 2G -hda path/to/vm.qcow2
```
Please report any log you may have running these commands including the logs in the framebuffer of the VM.

Thank you for your time!

**Comment by symeonp** [comment]
HI Quentin01,

Thank you so much for your quick response.
I've ran the command and can confirm it's an issue with nested virtualisation as this leads to the booting loop again ...
My VMWare is: Professional Version 12.2.1 (18811640)

Please let me try VirtualBox or another Windows host... 

Many thanks again!

**Comment by Quentin01** [comment]
OK, let us know if using another hypervisor or host fixes the issue.

**Comment by symeonp** [comment]
Hi Quentin01,

Can confirm it worked with VirtualBox - probably a glitch with VMWare Fusion...

Many thanks again!
