### ISSUE TITLE
Hint :Failed to mount /home/reven， dependency failed for local file systems

### ISSUE THREAD

**Issue by MS008** [tetrane/reven-community#27]
**Describe the bug**
Error when starting Reven virtual machine, 
Hint:  Failed to mount /home/reven， dependency failed for local file systems
As shown below
![000](https://user-images.githubusercontent.com/29914124/178438412-7f66c602-e080-4e14-8fda-442518f57eff.png)
![001](https://user-images.githubusercontent.com/29914124/178438450-224d1981-0002-4621-b563-fdc56299e5ea.png)

**To Reproduce**
I followed the steps below to install,
https://doc.tetrane.com/latest/Installation/Server/REVEN-in-a-VM/VMware.html

**Screenshots**
![000](https://user-images.githubusercontent.com/29914124/178440943-90476bd7-10c3-49d8-9df6-c25cfa970f87.png)

**Host Environment**
- System: Windows 11 (Home )
- VMware Workstation 16 Pro
- REVEN Version ( 2.11.0)
- REVEN Edition ("Free Edition")
- REVEN Package ( VM) 
- Additional information of interest? 
- 
Because of the prompt  "Can't find ext4 filesystem", it seems to be a problem with the loading of the disk, so I modified the virtual device node of the disk.
![002](https://user-images.githubusercontent.com/29914124/178440329-362cb65d-d7f2-4486-8ce0-92de88a319ac.png)

![003](https://user-images.githubusercontent.com/29914124/178440371-a7847b75-1741-442b-8346-99dc6f69351c.png)
I changed the node of the attached data disk to SCSI 0:0 and the node of the main disk to SCSI 0:1

![004](https://user-images.githubusercontent.com/29914124/178440642-09635813-43aa-44f2-8dc1-25c14efbc463.png)

Can't find ext4 filesystem problem solved, but still can't start normally.

How can I get it to start normally?

**Comment by Hyask** [comment]
Hi,

Thanks for trying REVEN!
Regarding your problem, I have personally no access to VMWare, thus I'm not sure about your drive configuration, but here are some hints:
  * It's absolutely necessary that the data drive is exposed in second position, so that it will be named `/dev/sdb` by the Linux kernel.
  * My intuition leads me to think that your data drive may have been already formatted to something else than `ext4`. That would probably produce the `Can't find ext4 filesystem` error, and that would indicate that the drive was at the right place. Swapping the drives as you did would indeed make this specific error disappear, as `/dev/sdb` would now be the boot drive and is also `ext4` formatted, but this can't make things to work without further configuration in the VM.
  * As a first step, I suggest trying again with a new data drive, attached at the right position (SCSI 0:1), but first make sure that this new data drive is not formatted, and has no partition either, so that the VM will be able to make it `ext4` without error.

Hope this helps, and please let me know how it goes.

**Comment by MS008** [comment]
Oh, Try again, I deleted all the partitions of the new hard disk, and it was not formatted. The disk was replaced with MBR, but it still prompted "Can't find ext4 filesystem".    Are there any other details to pay attention to?

**Comment by Hyask** [comment]
Just to be sure, I made a test on VirtualBox, and was able to reproduce the same issue, by using a data disk that contained only an MBR partition table (with no partition in it!). The data disk really must be empty, without even a partition table.

You can verify that by attaching the disk to another Linux system and running the following:  
`file -sL /dev/sdX` with `sdX` being the exposed data disk.  
The command must not return something like `DOS/MBR boot sector`, but only `data`. If something other than `data` is returned, then you must wipe the data disk with a command like the following:  
`sudo dd if=/dev/zero of=/dev/sdX`

Once done, you can boot up the REVEN VM again, and it should successfully reach its "First start" target.

Hope this helps

**Comment by MS008** [comment]
> Just to be sure, I made a test on VirtualBox, and was able to reproduce the same issue, by using a data disk that contained only an MBR partition table (with no partition in it!). The data disk really must be empty, without even a partition table.
> 
> You can verify that by attaching the disk to another Linux system and running the following: `file -sL /dev/sdX` with `sdX` being the exposed data disk. The command must not return something like `DOS/MBR boot sector`, but only `data`. If something other than `data` is returned, then you must wipe the data disk with a command like the following: `sudo dd if=/dev/zero of=/dev/sdX`
> 
> Once done, you can boot up the REVEN VM again, and it should successfully reach its "First start" target.
> 
> Hope this helps


Thank you very much, it is really necessary to delete all the data of the entire disk,  By the way , it is recommended to declare it on the documentation.

![005](https://user-images.githubusercontent.com/29914124/178469977-40930ebd-3244-4ab8-9378-7b526700336f.png)

**Comment by Hyask** [comment]
Yes! I'm glad it worked.

I'm right away adding some details about that in our documentation for the next release.

Thanks for your report, and enjoy REVEN :smile:
