### ISSUE TITLE
[BUG] The detect_use_after_free_2.7 and detect_buffer_overflow script prompts an error

### ISSUE THREAD

**Issue by MS008** [tetrane/reven-community#28]
**Describe the bug**
I'm trying to dig out the vulnerability of  an GUI software under Windows system,

It seems the program has a lot of memory request and release operations
![1142314](https://user-images.githubusercontent.com/29914124/179693706-de621aa8-3c44-41dc-aacd-8be4468a4340.png)

After running the script（detect_use_after_free_2.7）, hints  "Two consecutives allocs found" and "ValueError: Memory range size must be greater than zero",
![111](https://user-images.githubusercontent.com/29914124/179682271-b27fb904-c5d5-428a-81bc-f2ee97fcf42f.png)
![222](https://user-images.githubusercontent.com/29914124/179682309-9440d451-105d-4dc0-9ca8-21e204a9e2a3.png)

After running the script (detect_buffer_overflow).hints "RuntimeError: Invalid subrange",
![3333](https://user-images.githubusercontent.com/29914124/179692122-65f9f832-f491-494e-9f3f-96e89236731a.png)
![4444](https://user-images.githubusercontent.com/29914124/179692149-06553945-103f-441e-978f-9fbd56c8ebf7.png)

**To Reproduce**

1.Record the scene.
2. run script.
3. See error.

**Expected behavior**
Displays whether there are UAF vulnerabilities.

**Screenshots**
Prompt "Two consecutives allocs found"
and "ValueError: Memory range size must be greater than zero"
![111](https://user-images.githubusercontent.com/29914124/179682271-b27fb904-c5d5-428a-81bc-f2ee97fcf42f.png)
![222](https://user-images.githubusercontent.com/29914124/179682309-9440d451-105d-4dc0-9ca8-21e204a9e2a3.png)

**Host Environment**
- REVEN Version (2.11.0)
- REVEN Edition ("Free Edition")
- REVEN Package (VM) 

**Conditions of occurrence**
- Target environment  (Windows, 7  64 bits)

How to  avoid the error? what changes should i make

**Comment by Quentin01** [comment]
Hello and thank you for your report!

This looks like some incompatibilities between the UAF/buffer overflow scripts and REVEN 2.11.

Fortunately, you might be able to fix the issues with small changes to the `detect_use_after_free_2.7` and `detect_buffer_overflow` scripts.

### 1. Fixing the "invalid subrange" in the uaf_analyze_function

In the scripts, locate the lines:

```py
        # Build the event by reading the needed registers
        if event_class == AllocEvent:
            current_address, size = retrieve_event_info(ctx, ctx_ret)

            # Filter the alloc failing
            if current_address == 0x0:
                continue
```

Then, change the code as follows:

```diff
         # Build the event by reading the needed registers
         if event_class == AllocEvent:
             current_address, size = retrieve_event_info(ctx, ctx_ret)
 
             # Filter the alloc failing
-            if current_address == 0x0:
+            if current_address == 0x0 or size == 0:
                 continue
```


### 2. Fixing the AttributeError in the filter_ functions

This one is caused by cases where `malloc` or `free` occurs inside of functions whose symbol is unknown

In the scripts, look for the `filter_*` functions:  

```py
if search_windows_malloc:
    def filter_in_realloc(location, caller_location):
        return location.binary == caller_location.binary and caller_location.symbol.name == "realloc"

...

if search_pool_allocation:
    # Search for allocations with ExAllocatePool...
    def filter_ex_allocate_pool(location, caller_location):
        return location.binary == caller_location.binary and caller_location.symbol.name.startswith("ExAllocatePool")

    for symbol in server.ossi.symbols(r'^ExAllocatePool', binary_hint=r'ntoskrnl.exe'):
        retrieve_events_for_symbol(alloc_dict, AllocEvent, symbol, retrieve_alloc_info_with_size_as_second_argument,
                                   filter_ex_allocate_pool)

    # Search for deallocations with ExFreePool...
    def filter_ex_free_pool(location, caller_location):
        return location.binary == caller_location.binary and caller_location.symbol.name == "ExFreePool"

    for symbol in server.ossi.symbols(r'^ExFreePool', binary_hint=r'ntoskrnl.exe'):
        retrieve_events_for_symbol(alloc_dict, FreeEvent, symbol, retrieve_free_info_with_address_as_first_argument,
                                   filter_ex_free_pool)

if search_linux_malloc:
    def filter_in_realloc(location, caller_location):
        return (location.binary == caller_location.binary
                and caller_location.symbol is not None
                and caller_location.symbol.name in ["realloc", "__GI___libc_realloc"])
```

Then, add the following guards to prevent the error:

```diff
 if search_windows_malloc:
     def filter_in_realloc(location, caller_location):
-        return location.binary == caller_location.binary and caller_location.symbol.name == "realloc"
+        return location is not None and caller_location is not None and caller_location.symbol is not None and location.binary == caller_location.binary and caller_location.symbol.name == "realloc"
 
...

 if search_pool_allocation:
     # Search for allocations with ExAllocatePool...
     def filter_ex_allocate_pool(location, caller_location):
-        return location.binary == caller_location.binary and caller_location.symbol.name.startswith("ExAllocatePool")
+        return location is not None and caller_location is not None and caller_location.symbol is not None and location.binary == caller_location.binary and caller_location.symbol.name.startswith("ExAllocatePool")

     for symbol in server.ossi.symbols(r'^ExAllocatePool', binary_hint=r'ntoskrnl.exe'):
         retrieve_events_for_symbol(alloc_dict, AllocEvent, symbol, retrieve_alloc_info_with_size_as_second_argument,
                                    filter_ex_allocate_pool)

     # Search for deallocations with ExFreePool...
     def filter_ex_free_pool(location, caller_location):
-        return location.binary == caller_location.binary and caller_location.symbol.name == "ExFreePool"
+        return location is not None and caller_location is not None and caller_location.symbol is not None and location.binary == caller_location.binary and caller_location.symbol.name == "ExFreePool"

     for symbol in server.ossi.symbols(r'^ExFreePool', binary_hint=r'ntoskrnl.exe'):
         retrieve_events_for_symbol(alloc_dict, FreeEvent, symbol, retrieve_free_info_with_address_as_first_argument,
                                    filter_ex_free_pool)
 
 if search_linux_malloc:
     def filter_in_realloc(location, caller_location):
-         return (location.binary == caller_location.binary
+         return (location is not None
+                and caller_location is not None
                 and location.binary == caller_location.binary
                 and caller_location.symbol is not None
                 and caller_location.symbol.name in ["realloc", "__GI___libc_realloc"])
```

### 3. Fixing the "invalid subrange" in bof_analyze_function

Locate the `get_alloc_free_pairs` function:

```py
def get_alloc_free_pairs(events, errors=None):
    previous_event = None
    for event in events:
        if isinstance(event, AllocEvent):
            if previous_event is None:
                pass
            elif isinstance(previous_event, AllocEvent):
                if errors is not None:
                    errors.append("Two consecutives allocs found")
        elif isinstance(event, FreeEvent):
            if previous_event is None:
                continue
            elif isinstance(previous_event, FreeEvent):
                if errors is not None:
                    errors.append("Two consecutives frees found")
            elif isinstance(previous_event, AllocEvent):
                yield (previous_event, event)
        else:
            assert 0, ("Unknown event type: %s" % type(event))

        previous_event = event

    if isinstance(previous_event, AllocEvent):
        yield (previous_event, None)
```

Then change it in the following way:

```diff
 def get_alloc_free_pairs(events, errors=None):
     previous_event = None
     for event in events:
         if isinstance(event, AllocEvent):
             if previous_event is None:
                 pass
             elif isinstance(previous_event, AllocEvent):
                 if errors is not None:
                     errors.append("Two consecutives allocs found")
         elif isinstance(event, FreeEvent):
             if previous_event is None:
                 continue
             elif isinstance(previous_event, FreeEvent):
                 if errors is not None:
                     errors.append("Two consecutives frees found")
             elif isinstance(previous_event, AllocEvent):
+                if previous_event.tr_end > event.tr_begin:
+                    if errors is not None:
+                        errors.append("Overlapping alloc/free")
+                else:
-                yield (previous_event, event)
+                    yield (previous_event, event)
         else:
             assert 0, ("Unknown event type: %s" % type(event))
 
         previous_event = event
 
     if isinstance(previous_event, AllocEvent):
         yield (previous_event, None)
```

This should fix the issues your reported. Please note that the vulnerability detection scripts specifically are research scripts and have the limitations outlined in the [accompanying articles](https://blog.tetrane.com/tag/vulnerability-detection/). 

Feel free to come back to us for further investigation should new issues arise.

Happy REVEN-ing!

**Comment by MS008** [comment]
I changed detect_use_after_free_2.7 and detect_buffer_overflow script,  

detect_use_after_free_2.7 throw an Exception, as shown below，

It's hits  AttributeError: 'NoneType' object has no attribute 'tainted_registers'
![图片1](https://user-images.githubusercontent.com/29914124/179900434-a16f110a-a267-4f71-b61e-374a0d6efb57.png)

thanks again.

**Comment by dureuill** [comment]
Hello,

Investigating the error, the root cause looks like the same error of overlapping `malloc`/`free` that was happening in the buffer overflow script (here it causes the taint to have an empty set of tainted contexts, which causes the `taint.state_at` function to unexpectedly return `None`). 

If you didn't already, applying the fix of solution (3) 'Fixing the "invalid subrange" in bof_analyze_function'  from the [message from my colleague](https://github.com/tetrane/reven-community/issues/28#issuecomment-1188787639) to the `detect_use_after_2.7.ipynb` script (which has a similar `get_alloc_free_pairs` function) may fix the error.

If it isn't sufficient, we can handle the condition locally, by modifying the `start_alloc_address_taint` function.

```diff
 def start_alloc_address_taint(server, alloc_event, free_event):
     # Setup the first taint [alloc; free]
     tainter = reven2.preview.taint.Tainter(server.trace)
     taint = tainter.simple_taint(
         tag0="rax" if alloc_event.tr_end.context_before().is64b() else "eax",
         from_context=alloc_event.tr_end.context_before(),
         to_context=free_event.tr_begin.context_before() + 1,
         is_forward=True
     )
 
     # Setup the second taint [free; [
     state_before_free = taint.state_at(free_event.tr_begin.context_before())

+    if state_before_free is None:
+        return None

     # `rcx` is lost during the execution of the free in theory
     # `rsp` is non-useful if we have it
     tag0_regs = filter(
         lambda x: x[0].register.name not in ['rcx', 'rsp'],
         state_before_free.tainted_registers()
     )
``` 

Then by modifying the callers of this function to accomodate for the now possible `None` value: in `uaf_analyze_function`:

```diff
         else:
             print("Phys:0x%x: Allocated at #%d (0x%x of size 0x%x) and freed at #%d (0x%x)" % (physical_address,
                   alloc_event.tr_begin.id, alloc_event.memory_range.logical_address, alloc_event.memory_range.size,
                   free_event.tr_begin.id, free_event.logical_address))
             print("    Warning: Memory history optimization disabled because we couldn't "
                   "translate all the memory pages")
             print()
 
         # Setup the slicing
         taint = start_alloc_address_taint(server, alloc_event, free_event)
+        if taint is None:
+            continue
         # Iterate on the slice
         access_count = 0
```

This should fix the immediately outstanding issue. 

However, the underlying issue is that the `malloc`/`free` detection routine returns allocation events that overlap with deallocation events, which violates an assumption of the algorithm.

This may point to inaccuracies in the heuristics that we are using to detect the allocation and deallocation events.

There's a cell with a code comment `# Print the events` in the notebook. It would be interesting to look for inconsistencies in these events on your scenario, maybe it would point in the right direction as to what the issue with the heuristics might be. You may need to do so without the fix to `get_alloc_free_pairs`, so that the overlapping events are visible.

Then, you could try to look at the heuristics we use to find the allocation/deallocation pairs. One entry point is the  cell where we define which function calls to identify as allocation, and which function calls to identify as deallocation (the cell containing `if search_malloc:`).

I hope this helps!

**Comment by MS008** [comment]
Thank you so much,  it should be the overlap issue caused by  'taint.state_at ' function  return None,  it is displayed normally after modification.

**Comment by dureuill** [comment]
Great to know, I hope the scripts and REVEN will help you analyze the vulnerability in the GUI software!
